

```{r libraries}

library(tidyverse)
library(ggplot2)
library(zoo)

```

```{r test}

library(readxl)
RGDP_Data <- read_excel("RGDP Data.xlsx")

# extracting the most revised values/recent data
latest_data <- RGDP_Data$ROUTPUT24Q1

# creating a lag for all quarters
lag(latest_data)


check <- data.frame(RGDP_Data$DATE, log(latest_data), lag(log(latest_data)))

check <- check %>% 
  rename(c("Date" = "RGDP_Data.DATE",
           "Raw Data" = "log.latest_data.",
           "First Lag" = "lag.log.latest_data.."))

check <- check[-1,] %>% 
  mutate(growth_rate = (`Raw Data` - `First Lag`)/`First Lag` * 100)

# formatting the data variable in terms of year and quarters
Dates <- gsub(":", " ", check$Date) 
check <- check %>% 
  mutate(Time = as.yearqtr(Dates)) %>% 
  select(c(Time, growth_rate)) %>% 
  mutate(growth_rate = as.numeric(growth_rate))

## EXPLAIN EVERYTHING 
# variance of initial years (prior to them changing to GDP) seems higher 
plot(c(1:307), check$growth_rate, type = "l", lwd = 1)

ggplot(check, aes(Time, growth_rate)) + 
  geom_point() + 
  geom_line()

# add line to show where they changed computation method 
# add line to show Covid as well 

```

### AR Function & Model 

```{r autoregression}

fitAR=function(Y,p,h){
  
  #Inputs: Y- predicted variable,  p - AR order, h -forecast horizon
  
  
  aux=embed(Y,p+h) #create p lags + forecast horizon shift (=h option)
  y=aux[,1] #  Y variable aligned/adjusted for missing data due to lags
  X=as.matrix(aux[,-c(1:(ncol(Y)*h))]) # lags of Y (predictors) corresponding to forecast horizon (prevent leakage)  

    X.out=tail(aux,1)[1:ncol(X)] #retrieve last p observations 

  

    model=lm(y~X) #estimate direct h-step AR(p) by OLS 
    coef=coef(model) #extract coefficients

  

  pred=c(1,X.out)%*%coef #make a forecast using the last few observations: a direct h-step forecast.
  #note the addition of a constant to the test observation vector
  
  rmsfe=sqrt(sum(model$residuals^2)/nrow(X)) #get unadjusted rmsfe (ignoring estimation uncertainty)
  
  return(list("model"=model,"pred"=pred,"coef"=coef, "rmsfe"=rmsfe)) #save estimated AR regression, prediction, and estimated coefficients
}

test <- as.matrix(log(check$growth_rate))


fitAR(test, 2, 2)

```


### Preparing for Advanced AR Model 


```{r advanced AR prep}

# calculating mean first revision percentage changes 

# extracting initial values of all variables
# take pre-COVID data
data_65q3_onwards <- RGDP_Data[c(75:292), c(1:219)]  %>% 
  subset(select = -DATE) 

m1 <- as.matrix(data_65q3_onwards) 

data_65q3_onwards <- matrix(m1, ncol = ncol(data_65q3_onwards), dimnames = NULL)

# extracting initial values of all variables
initial_values <- diag(data_65q3_onwards)


# extracting first revision values of all variables
first_revision_data <- RGDP_Data[c(75:292), c(1:219)] %>% 
  select(-c(1, 2)) 

# base dataset showing the GDP values across quarters 

GDP_across_q <- RGDP_Data[c(74:293), c(1:220)] %>%
  subset(select = -DATE) %>%
  mutate_all(as.numeric)

colnames(GDP_across_q) <- NULL

GDP_across_q <- as.matrix(GDP_across_q) 

lagged_GDP_across_q <- lag(GDP_across_q)

df <- 100 * (GDP_across_q - lagged_GDP_across_q)/lagged_GDP_across_q 

# Removing the first and last row since we had added those to compute the lag.
df <- df[-c(1, 220),]

# Revised values is a data frame that shows the growth rate of each quarter as compared to the previous quarter, across revisions. For instance, revision0 is the initial growth rate for each quarter, and revision1 shows the growth rate after values have been revised. 

revised_growth <- data.frame(matrix(NA, nrow = 218, ncol = 0))

for (i in 0:40){
  na_vector = c(replicate(218, NA)) 
  na_vector = as.numeric(na_vector)
  
  values <- diag(df)
  
  col_name = paste0("revision", i)
  
  na_vector[1:(218-i)] = values[1:(218-i)]
  revised_growth[[`col_name`]] = na_vector
  
  df <- df[,-c(1)]
}


# Now, we are looking into how the growth rates change due to revision. 
lagged_growth <- revised_growth[, -c(ncol(revised_growth))]
revised_growth <- revised_growth[,-c(1)]

# We're taking the average of the change in growth per revision 
change_in_growth <- 100*((revised_growth - lagged_growth)/lagged_growth)

change_in_growth[sapply(change_in_growth, is.infinite)] <- NA
  
change_in_growth <- change_in_growth %>% apply(2, mean, na.rm = TRUE)


```


### Advanced AR Model 


```{r advanced AR}

example_q = "2014 Q1"
example_yq = as.yearqtr(example_q)

# Formatting dataframe of quarters and their estimated values
working_df = RGDP_Data[, -c(1)] %>%
  mutate_all(as.numeric)

colnames(working_df) <- sapply(seq(as.Date(as.yearqtr("1965 Q4", format = "%Y Q%q")), by="quarter", length.out = ncol(working_df)), function(x) format(as.yearqtr(x), format = "%Y Q%q"))
rownames(working_df) <- sapply(seq(as.Date(as.yearqtr("1947 Q1", format = "%Y Q%q")), by="quarter", length.out = nrow(working_df)), function(x) format(as.yearqtr(x), format = "%Y Q%q"))

# Calculating growth rate of each quarter
lagged_working_df = lag(working_df)
perc_change_df = (100 * (working_df - lagged_working_df) / lagged_working_df)[-c(1),]

# Split dataframe into 10 years before target date and current value of growth for quarters more than 10 years ago
ten_year_mark = (example_yq - 10 - as.yearqtr("1947 Q1", format = "%Y Q%q")) * 4
end_of_row_mark = (example_yq - as.yearqtr("1947 Q1", format = "%Y Q%q")) * 4 - 1

# Most recent values for start of time to 10 years before target date
ancient_values <- perc_change_df[1:ten_year_mark,][[`example_q`]]

# All other values
recent_values <- perc_change_df[(ten_year_mark + 1): end_of_row_mark,][[`example_q`]]
  #select((which(names(.) == toString(example_yq - 10)) + 2) : toString(example_yq))

# Applying approximation of final growth numbers on recent values
forecast_growth = recent_values #c(replicate(length(recent_values), NA))
for (i in 1:length(recent_values)){
  for (j in 1:i){
    forecast_growth[i] = forecast_growth[i] * (1 + (change_in_growth[40 - j] / 100) )
  }
}

all_data = c(ancient_values, forecast_growth)

fitAR=function(Y,p,h){
  
  #Inputs: Y- predicted variable,  p - AR order, h -forecast horizon
  
  aux=embed(Y,p+h) #create p lags + forecast horizon shift (=h option)
  y=aux[,1] #  Y variable aligned/adjusted for missing data due to lags
  X=as.matrix(aux[,-c(1:(ncol(Y)*h))]) # lags of Y (predictors) corresponding to forecast horizon (prevent leakage)  

    X.out=tail(aux,1)[1:ncol(X)] #retrieve last p observations 

    model=lm(y~X) #estimate direct h-step AR(p) by OLS 
    coef=coef(model) #extract coefficients

  pred=c(1,X.out)%*%coef #make a forecast using the last few observations: a direct h-step forecast.
  #note the addition of a constant to the test observation vector
  
  rmsfe=sqrt(sum(model$residuals^2)/nrow(X)) #get unadjusted rmsfe (ignoring estimation uncertainty)
  
  return(list("model"=model,"pred"=pred,"coef"=coef, "rmsfe"=rmsfe)) #save estimated AR regression, prediction, and estimated coefficients
}

test2 <- as.matrix(log(all_data))

AR_fitted_model = fitAR(test2, 2, 2)

example_forecast = AR_fitted_model$pred
example_model = AR_fitted_model$model
example_forecast

plot(c(all_data), type = "l", lwd = 1)
plot(c(all_data, example_forecast), type = "l", lwd = 1)

```

