
```{r import, warning = FALSE, results= "hide", echo = FALSE}

source("GDP Cleaning.R")
source("inputs.R")

```


# Basic GDP Prep 

```{r gdp prep, warning=FALSE}

spliced_GDP <- data_splice(RGDP_Data, "1947 Q1", "2023 Q4", "1965 Q4", 
                           "2024 Q1", example_startyq, example_endyq, 3, 0)

post_prep_gdp <- prep_func(spliced_GDP, 40)
post_prep_gdp_df <- post_prep_gdp$df
post_prep_gdp_delta = post_prep_gdp$delta

# revise GDP values

# note that the last input should be in a string format
sliced_perc_change <- data_splice(perc_change_df, "1947 Q2", "2023 Q4", 
                                  "1965 Q4", "2024 Q1", 
                                  example_startq, example_endq, 2, 1)
all_GDP_data <- revise_values(sliced_perc_change, post_prep_gdp_delta, 
                              example_startq, example_endq)

GDPGrowth_ts <- ts(all_GDP_data, 
                  start = c(start_y, start_q), 
                  end = c(end_y, end_q), 
                  frequency = 4)
```


# ADL Model - Splicing Function 

```{r adl splice function}

ADL_splice <- function(data, window_start, window_end){
  start_rownum = which(grepl(window_start, data$Date))
  end_rownum = which(grepl(window_end, data$Date))

  output <- data[start_rownum:end_rownum+1, ]
  
  return(output)
}

```

# Functions for AIC selection

```{r prep for AIC selection}

# List of variables
variables <- c("baa_aaa_ts", "tspread_ts", "fred_hstarts_ts", "consent_ts")
n <- length(variables)

# formula to find best number of lags given a variable
find_best_lag <- function(data, response, variable, max_lags) {
  best_aic <- Inf
  best_lag <- 0
  
  for (lag in 1:max_lags) {
    # Build the model formula
    formula <- as.formula(paste(response, "~", paste("L(", variable, ",", 1:lag, ")", sep = "", collapse = " + ")))
    
    # Fit the model
    model <- dynlm(formula, data = data)
    
    # Calculate AIC
    aic <- AIC(model)
    
    # Update best lag if AIC improves
    if (aic < best_aic) {
      best_aic <- aic
      best_lag <- lag
    }
  }
  return(best_lag)
}

# function to generate a base formula to add on more variables later
generate_base_formula <- function(variable, lag){
  formula <- paste("GDPGrowth_ts ~", paste("L(", variable, ",", 1:lag, ")", sep = "", collapse = " + "))
  return(formula)
}

# function to extend the base formula 
extend_formula <- function(formula_str, new_variable, num_lags) {

  formula_components <- strsplit(formula_str, "~")[[1]] # Split the formula string into its components
  response_var <- trimws(formula_components[1])         # Extract the left-hand side (response variable)
  explanatory_vars <- trimws(formula_components[2])     # Extract the right-hand side (explanatory variables)
  
  if (grepl(paste0("\\b", new_variable, "\\b"), explanatory_vars)) {  # Check if the new variable already exists
    return(formula_str)  
  }
  
  new_var_lags <- paste0("L(", new_variable, ", ", 1:num_lags, ")")   # Construct the part for the new variable and lags
  
  if (explanatory_vars == "") {
    new_formula <- paste(response_var, "~", paste(new_var_lags, collapse = " + "), sep = " ")
    return(new_formula)
  }
  
  new_formula <- paste(response_var, "~", explanatory_vars, "+", paste(new_var_lags, collapse = " + "), sep = " ")
  return(new_formula)
}
```

# Functions for individual ADL Model

```{r}

AICselection_indv <- function(Y_dataframe, variable) {
  df <- data.frame(Y_dataframe, variable)
  base_best_lag <- find_best_lag(df, "GDPGrowth_ts", "GDPGrowth_ts", 4)
  base_formula <- generate_base_formula("GDPGrowth_ts", base_best_lag)
  best_aic <- AIC(dynlm(as.formula(base_formula)))
  for (lag in 1:4) {
        formula <- as.formula(extend_formula(base_formula, variable, lag))
        model <- dynlm(formula, data = df)
        aic <- AIC(model)
        
        if (aic < best_aic) {
          best_aic <- aic
          best_lag <- lag
        }
  }
  formula <- extend_formula(base_formula, variable, best_lag)
  return(formula)
}

```

```{r}

# input model is the dynlm model churned out based on AIC selector 

pval_selection_indv <- function(model){
  coeftest <- coeftest(model)
  tidy_coeftest <- broom::tidy(coeftest) %>% 
    filter(p.value <= 0.10) %>% 
    select(term)
  
  if (sum(str_detect(tidy_coeftest$term, '(Intercept)')) > 0){
    # Intercept is significant; so remove it from the rows 
    tidy_coeftest = tidy_coeftest[-1,]
  }
  
  if (nrow(tidy_coeftest) == 0){
    lag_string = ""
  } else{
    lag_string = tidy_coeftest[[1]][1]
    
    for (i in 2:nrow(tidy_coeftest)){
      lag_string = paste(lag_string, tidy_coeftest[[1]][i], sep = " + ")
    }
  }
  
  model_string = paste("GDPGrowth_ts ~ ", lag_string)
  
  return(model_string)
}

# note that the output is a string


```

# Function for calculating next quarter prediction

```{r next quarter}

ADL_predict_1 <- function(Y_dataframe, X_dataframe, Y_string, X_string,
                          selectors, coefficients){
  
  input_string <- as.character(selectors)
  
  Y_lags <- str_count(input_string, Y_string) - 1
  X_lags <- str_count(input_string, X_string) 
  
  pred = coefficients[[1]]
  
  if (Y_lags == 0){
    if (X_lags == 0){
      # if Y_lags = 0 and X_lags = 0
      pred = pred
      print(pred)
    } 
    else {
      # if Y_lags = 0 and X_lags != 0
      for (i in 1:X_lags){
        coeff_n = 1 + Y_lags + i
        temp = (tail(X_dataframe, n = i)[1]) * coefficients[[coeff_n]]
        pred = pred + temp
      }
    }
  } else if (X_lags == 0){
    # if Y_lags != 0 and X_lags = 0
    for (j in 1:Y_lags){
      coeff_n = 1 + j
      temp = (tail(Y_dataframe, n = j)[1]) * coefficients[[coeff_n]]
      pred = pred + temp
    }
  } else {
    # if Y_lags != 0 and X_lags != 0 
      for (p in 1:Y_lags){
        coeff_n = 1 + p
        temp = (tail(Y_dataframe, n = p)[1]) * coefficients[[coeff_n]]
        pred = pred + temp
      }
      for (q in 1:X_lags){
        coeff_n = 1 + Y_lags + q
        temp = (tail(X_dataframe, n = q)[1]) * coefficients[[coeff_n]]
        pred = pred + temp
      }
    }
  
  return(pred)
}


```


# Function for calculating predictions for all time horizons

```{r predict all horizons}

ADL_predict_all <- function(Y_dataframe, X_dataframe, f_horizon){
  
  # extracting the names of the dataframes in string format
  Y_string <- as.character(substitute(Y_dataframe))
  X_string <- as.character(substitute(X_dataframe))
  
  # converting from time series class to dataframe for future use
  GDP_df <- as.data.frame(Y_dataframe)
  X_df <- as.data.frame(X_dataframe)
  
  # Formula recommended by AIC selector
  selectors_AIC <- AICselection_indv(X_dataframe, X_string)
  # model based on AIC selection
  model_AIC <- dynlm(as.formula(selectors_AIC),
        start = c(start_y, start_q), 
        end = c(end_y, end_q))
    
  # Formula recommended by p-value selector
  selectors_p <- pval_selection_indv(model_AIC)
  model_p <- dynlm(as.formula(selectors_p),
                     start = c(start_y, start_q), 
                     end = c(end_y, end_q))
    
  pred <- ADL_predict_1(Y_dataframe, X_dataframe, Y_string, X_string,
                        selectors_p, model_p$coefficients)
  
  if (f_horizon == 1){
    pred = pred
  } 
  else {
    for (i in 2:f_horizon){
      # shifting all Y values up by a quarter
      GDP_df <- lead(GDP_df, 1)
      # replace the NA in the last row with the prediction above
      GDP_df[nrow(GDP_df), "x"] <- pred
      
      GDPGrowth_ts <- ts(GDP_df, 
                  start = c(start_y, start_q), 
                  end = c(end_y, end_q), 
                  frequency = 4)
      
      # Formula recommended by AIC selector
      selectors_AIC <- AICselection_indv(Y_dataframe, X_string)
      # model based on AIC selection
      model_AIC <- dynlm(as.formula(selectors_AIC),
            start = c(start_y, start_q), 
            end = c(end_y, end_q))
        
      # Formula recommended by p-value selector
      selectors_p <- pval_selection_indv(model_AIC)
      model_p <- dynlm(as.formula(selectors_p),
                         start = c(start_y, start_q), 
                         end = c(end_y, end_q))
        
      pred <- ADL_predict_1(Y_dataframe, X_dataframe, Y_string, X_string,
                            selectors_p, model_p$coefficients)
      
    }
  }
  
  print(GDP_df)
  return (pred)
}


```


# ADL Model - BAA-AAA Spread 

```{r adl model baa-aaa}

baa_aaa <- read_excel("../Data/FRED BAA-AAA Data.xls", 
                      col_names = c("Date", "Spread")) %>% 
  mutate(Date = as.yearqtr(Date), 
         Spread = as.numeric(Spread))

baa_aaa <- ADL_splice(baa_aaa, example_startyq, example_endyq)
  
baa_aaa_ts <- ts(baa_aaa$Spread, 
                start = c(start_y, start_q), 
                end = c(end_y, end_q), 
                frequency = 4)

plot(merge(as.zoo(GDPGrowth_ts), as.zoo(baa_aaa_ts)), 
     plot.type = "single", 
     col = c("darkred", "steelblue"),
     lwd = 2,
     xlab = "Date",
     ylab = "",
     main = "BAA-AAA Spread & GDP Growth over Time")

legend("topright", 
       legend = c("GDP Growth", "BAA-AAA Spread"),
       col = c("darkred", "steelblue"),
       lwd = c(1, 1),
       cex = 0.5)

# model based on AIC selection
ADL_BAA_AAA <- 
  dynlm(as.formula(AICselection_indv(GDPGrowth_ts, "baa_aaa_ts")),
          start = c(start_y, start_q), 
          end = c(end_y, end_q))

BAA_AAA_selectors_AIC <- AICselection_indv(GDPGrowth_ts, "baa_aaa_ts")

# model further narrowed down based on p-values
BAA_AAA_selectors_p <- pval_selection_indv(ADL_BAA_AAA)

ADL_BAA_AAA_f <- dynlm(as.formula(BAA_AAA_selectors_p),
                       start = c(start_y, start_q), 
                       end = c(end_y, end_q))


pred_2021q1_AIC_only <- ADL_predict_1(GDPGrowth_ts, baa_aaa_ts, 
                                      "GDPGrowth_ts", "baa_aaa_ts",
                                      BAA_AAA_selectors_AIC, ADL_BAA_AAA$coefficients)
pred_2021q1_p_val <- ADL_predict_1(GDPGrowth_ts, baa_aaa_ts, 
                                   "GDPGrowth_ts", "baa_aaa_ts",
                                   BAA_AAA_selectors_p, ADL_BAA_AAA_f$coefficients)
print(pred_2021q1_AIC_only)
print(pred_2021q1_p_val)
# true value is 1.28 for reference

ADL_predict_all(GDPGrowth_ts, baa_aaa_ts, 4)

```


# ADL Model - Treasury Spread 

```{r adl model treasury}

tspread <- read_excel("../Data/FRED Treasury Spread.xls", col_names = c("Date", "Spread")) %>% 
  mutate(Date = as.yearqtr(Date), 
         Spread = as.numeric(Spread))

# NOTE: tspread is only from 1976 Q4 onward, so we can't accept forecast horizons earlier, at least not for this ADL model

tspread <- ADL_splice(tspread, example_startyq, example_endyq)

tspread_ts <- ts(tspread$Spread, 
                start = c(start_y, start_q), 
                end = c(end_y, end_q), 
                frequency = 4)

plot(merge(as.zoo(GDPGrowth_ts), as.zoo(tspread_ts)), 
     plot.type = "single", 
     col = c("darkred", "steelblue"),
     lwd = 2,
     xlab = "Date",
     ylab = "",
     main = "Treasury Spread & GDP Growth over Time")
legend("topright", 
       legend = c("GDP Growth", "Treasury Spread"),
       col = c("darkred", "steelblue"),
       lwd = c(1, 1),
       cex = 0.5)

# estimating the ADL(3,4) model of GDP growth

ADL_tspread34 <- 
  dynlm(GDPGrowth_ts ~ 
          L(GDPGrowth_ts) + L(GDPGrowth_ts, 2) + L(GDPGrowth_ts, 3) + 
          L(tspread_ts) + L(tspread_ts, 2),
          start = c(start_y, start_q), 
          end = c(end_y, end_q))

tspread_coefficients <- ADL_tspread34$coefficients

coeftest(ADL_tspread34)

AICselection_indv(tspread_ts, "tspread_ts")

```


# ADL Model - FRED Hstarts

```{r adl model fred hstarts}

fred_hstarts <- read_excel("../Data/FRED Hstarts.xls", col_names = c("Date", "Spread")) %>% 
  mutate(Date = as.yearqtr(Date), 
         Spread = as.numeric(Spread))

fred_hstarts <- ADL_splice(fred_hstarts, example_startyq, example_endyq)

fred_hstarts_ts <- ts(fred_hstarts$Spread, 
                start = c(start_y, start_q), 
                end = c(end_y, end_q), 
                frequency = 4)

plot(merge(as.zoo(GDPGrowth_ts), as.zoo(fred_hstarts_ts)), 
     plot.type = "single", 
     col = c("darkred", "steelblue"),
     lwd = 2,
     xlab = "Date",
     ylab = "",
     main = "Housing Starts & GDP Growth over Time")
legend("topright", 
       legend = c("GDP Growth", "Housing Starts"),
       col = c("darkred", "steelblue"),
       lwd = c(1, 1),
       cex = 0.5)

# estimating the ADL(3,4) model of GDP growth

ADL_fred_hstarts31 <- 
  dynlm(GDPGrowth_ts ~ 
          L(GDPGrowth_ts) + L(GDPGrowth_ts, 2) + L(GDPGrowth_ts, 3) +
          L(fred_hstarts_ts),
          start = c(start_y, start_q), 
          end = c(end_y, end_q))

fred_hstarts_coefficients <- ADL_fred_hstarts31$coefficients

coeftest(ADL_fred_hstarts31)

AICselection_indv(fred_hstarts_ts, "fred_hstarts_ts")

```


# ADL Model - Consumer Sentiment

```{r adl model consent}

consent <- read_excel("../Data/FRED Consumer Sentiment.xls", col_names = c("Date", "Spread")) %>% 
  mutate(Date = as.yearqtr(Date), 
         Spread = as.numeric(Spread))

consent <- ADL_splice(consent, example_startyq, example_endyq)

consent_ts <- ts(consent$Spread, 
                start = c(start_y, start_q), 
                end = c(end_y, end_q), 
                frequency = 4)

plot(merge(as.zoo(GDPGrowth_ts), as.zoo(consent_ts)), 
     plot.type = "single", 
     col = c("darkred", "steelblue"),
     lwd = 2,
     xlab = "Date",
     ylab = "",
     main = "Consumer Sentiment & GDP Growth over Time")
legend("topright", 
       legend = c("GDP Growth", "Consumer Sentiment"),
       col = c("darkred", "steelblue"),
       lwd = c(1, 1),
       cex = 0.5)

# estimating the ADL(3,1) model of GDP growth

ADL_consent31 <- 
  dynlm(GDPGrowth_ts ~ 
          L(GDPGrowth_ts) + L(GDPGrowth_ts, 2) + L(GDPGrowth_ts, 3) +
          L(consent_ts),
          start = c(start_y, start_q), 
          end = c(end_y, end_q))

consent_coefficients <- ADL_consent31$coefficients

coeftest(ADL_consent31)

AICselection_indv(consent_ts, "consent_ts")
```

# ADL Combined Model selection

```{r combined ADL without AR}

df <- data.frame(GDP_growth = GDPGrowth_ts, BAA_AAA_spread = baa_aaa_ts, treasury_spread = tspread_ts, housing_starts = fred_hstarts_ts, consumer_sentiment = consent_ts)

AICselection_without_AR <- function(df, variables) {
  base_best_lag <- find_best_lag(df, "GDPGrowth_ts", "GDPGrowth_ts", 4)
  base_formula <- "GDPGrowth_ts ~ "
  best_var <- 1
  
  while (best_var != 0) {
    best_aic <- Inf
    best_lag <- 0
    best_var <- 0
    
    for (i in seq_along(variables)) {
      var <- variables[i]
      
      for (lag in 1:4) {
        formula <- as.formula(extend_formula(base_formula, var, lag))
        model <- dynlm(formula, data = df)
        aic <- AIC(model)
        
        if (aic < best_aic) {
          best_aic <- aic
          best_lag <- lag
          best_var <- i
        }
      }
    }
    
    if (best_lag != 0) {
      base_formula <- extend_formula(base_formula, variables[[best_var]], best_lag)
      variables <- variables[-best_var]
    }
  }
  
  return(base_formula)
}

AICselection_without_AR(df, variables)
```


```{r combined ADL with AR}

df <- data.frame(GDP_growth = GDPGrowth_ts, BAA_AAA_spread = baa_aaa_ts, treasury_spread = tspread_ts, housing_starts = fred_hstarts_ts, consumer_sentiment = consent_ts)

AICselection_with_AR <- function(df, variables) {
  base_best_lag <- find_best_lag(df, "GDPGrowth_ts", "GDPGrowth_ts", 4)
  base_formula <- generate_base_formula("GDPGrowth_ts", base_best_lag)
  best_var <- 1
  
  while (best_var != 0) {
    best_aic <- AIC(dynlm(as.formula(base_formula), data = df))
    best_lag <- 0
    best_var <- 0
    
    for (i in seq_along(variables)) {
      var <- variables[i]
      
      for (lag in 1:4) {
        formula <- as.formula(extend_formula(base_formula, var, lag))
        model <- dynlm(formula, data = df)
        aic <- AIC(model)
        
        if (aic < best_aic) {
          best_aic <- aic
          best_lag <- lag
          best_var <- i
        }
      }
    }
    
    if (best_lag != 0) {
      base_formula <- extend_formula(base_formula, variables[[best_var]], best_lag)
      variables <- variables[-best_var]
    }
  }
  
  return(base_formula)
}

AICselection_with_AR(df, variables)

```
