
```{r import, warning = FALSE, results= "hide", echo = FALSE}

source("GDP Cleaning.R")
source("inputs.R")
source("DM_test.R")

```

### AR Function 

```{r AR function}

# Using the basic AR model from lecture 
# Inputs: Y - predicted variable, h - forecast horizon
# Iterates through p from 1 to 4 to find lowest rmsfe, uses that p to build model

fitAR=function(Y,h, dum){
  
  minimum = Inf
  
  for (p in 1:4){
    # create p lags + forecast horizon shift (=h option)
    aux = embed(Y, p+h)
    
    #  Y variable aligned/adjusted for missing data due to lags
    y = aux[,1] 
    
    # lags of Y (predictors) corresponding to forecast horizon (prevent leakage)
    X = as.matrix(aux[,-c(1:(ncol(Y)*h))])
  
    # retrieve last p observations
    X.out = tail(aux,1)[1:ncol(X)] 
    
    # cutting dummy to shape
    dum = tail(dum, length(y))
  
    # estimate direct h-step AR(p) by OLS 
    model = lm(y~X+dum) 
    
    # extract coefficients
    coef = coef(model)[1:(ncol(X)+1)]
  
    #make a forecast using the last few observations: a direct h-step forecast.
    pred = c(1,X.out)%*%coef 
    
    #note the addition of a constant to the test observation vector
    
    #get unadjusted rmsfe (ignoring estimation uncertainty)
    rmsfe = sqrt(sum(model$residuals^2)/nrow(X))
    aic = AIC(model)
    
    if(aic < minimum){
      minimum = aic
      best_rmsfe = rmsfe
      best_p = p
      best_model = model
      best_pred = pred
      best_coef = coef
    }
  }
  
  
  #save estimated AR regression, prediction, and estimated coefficients
  return(list("model"=best_model,"pred"=best_pred,"coef"=best_coef, "rmsfe" = best_rmsfe, "aic"=minimum, "p" = best_p)) 
}

```

### Basic AR Model 

```{r AR Model 1}

# Creating a test dataset that comprises the growth_rate from the check dataset

start_rownum = which(grepl(example_startyq, check$Time))
end_rownum = which(grepl(example_endyq, check$Time))

basic_AR_input <- check[start_rownum:end_rownum, ] %>% 
  select(growth_rate) %>% 
  as.matrix()

h = example_fhorizon

basic_AR_output <- fitAR(basic_AR_input, example_fhorizon, covid_dummy)

ar1_prediction = basic_AR_output$pred
ar1_rmsfe = basic_AR_output$rmsfe

```

# Predictions for Basic AR Model
```{r}
  fitAR_preds <- function(Y, h, dum) {
    preds = numeric(h)
    for(i in 1:h){
      #test_AR <- as.matrix(check$growth_rate)
      preds[i] = fitAR(Y, i, dum)$pred  ##2 is placeholder for input$lags
    }
    return(preds)
  }
```

### Advanced AR Model 

```{r Advanced AR model, warning = FALSE}

spliced_GDP <- data_splice(RGDP_Data, "1947 Q1", "2023 Q4", "1965 Q4", 
                           "2024 Q1", example_startyq, example_endyq, 3, 0)

post_prep_gdp <- prep_func(spliced_GDP, 40)
post_prep_gdp_df <- post_prep_gdp$df
post_prep_gdp_delta = post_prep_gdp$delta

#####################
## revise GDP values
#####################

# note that the last input should be in a string format
sliced_perc_change <- data_splice(perc_change_df, "1947 Q2", "2023 Q4", 
                                  "1965 Q4", "2024 Q1", 
                                  example_startq, example_endq, 2, 1)
all_GDP_data <- revise_values(sliced_perc_change, post_prep_gdp_delta, 
                              example_startq, example_endq)

advanced_AR_input <- as.matrix(all_GDP_data)


advanced_AR_output <- fitAR(advanced_AR_input, example_fhorizon, covid_dummy)

ar2_prediction = advanced_AR_output$pred
ar2_rmsfe = advanced_AR_output$msfe

```

### DM Test

```{r DM Test, warning = FALSE}

row_start_slice = (example_startyq - as.yearqtr("1947 Q2"))*4 + 1
row_last_slice = nrow(check) - (as.yearqtr("2023 Q4") - example_endyq)*4

real_values = as.matrix(check[row_start_slice:row_last_slice, ncol(check)])
start = example_endyq - 50/4
end = example_endyq

pred1 = rolling_window(basic_AR_input, 50, covid_dummy, real_values, start, end, h = example_fhorizon)$pred
pred2 = rolling_window(advanced_AR_input, 50, covid_dummy, real_values, start, end, h = example_fhorizon)$pred


dm_test(tail(real_values, 50), pred1, pred2, start, end)
# Basic vs Advanced values, Plots loss of basic - loss of advanced

```