*This page provides information on how to use the app and interpret results. Scroll to the bottom for basic information regarding the model methodologies.* 

## Using the App and Interpreting Results

&nbsp;

### **AR Models**

1. Select the start and end of your training window on the slider.
* As this suggests, the data selected in this interval will be used to train our models. 
* The window has to be at least 20 years long to ensure the models have sufficient data to be trained on. 

2. Select either the "Basic AR Model" or "Revised AR Model". 

3. Click "Show Prediction". 

Additional Notes:

* You can add up to 4 quarters worth of growth rates in the boxes at the bottom in order to predict growth rates slightly further into the future.  

&nbsp;

### **ADL Models**

1. Select the start and end of your training window on the slider. If you had already selected it for other models, you need not select it again. 

2. Select either "Individual ADL Model" or "Combined ADL Model"
* If you select "Individual ADL Model", you then also have to select an ADL predictor from the dropdown menu. 

3. Click "Show Prediction". 

Additional Notes:

* If you would like to test your own ADL indicator, you may upload it under the "Add a Predictor" tab. 
  + The data should only have two columns, with the left being quarters formatted as “YYYY QQ” and the left being the GDP growth rates.  
  
* [YAP ABOUT ROLLING TEST WINDOW HERE]

&nbsp;

### **Aggregate Model**

1. Select the start and end of your training window on the slider. If you had already selected it for other models, you need not select it again. 

2. Click "Show Prediction". 

&nbsp;

### **Results of AR & ADL Models**

* The output graph comprises recent actual growth rates, and an additional red line depicting the predicted growth rate. The graph only shows the last 10 quarters for easier visualisation
* The shaded blue regions around the prediction line are the 50% and 80% fan plots. It shows what the mean square forecast error, and we expect the majority of our forecasts to be within those intervals.
* If there is a pink shaded block in the window, that denotes a recession period in the past.
* Predicted growth rate values can be found below the plot. 
* [YAP ABOUT DIEBOLD MARINO RESULTS]

&nbsp;

### **Results of Aggregate Model**

* The results include those mentioned for AR and ADL Models, as well as some additional details.
* [WHAT IS IT DESCRIBED AS IN THE APP]

&nbsp;
&nbsp;

## Model Methodologies
&nbsp;

### **AR Models**

* The Basic AR Model is a simple autoregression model, using a maximum of 4 lags of GDP Growth rates.
* The Revised AR Model uses the same algorithm as the Basic AR Model, however, it modifies the inputted data. The data is modified using a Sigmoid function to better represent [CONTINUE YAPPING HERE]

&nbsp;

### **ADL Models**

* The individual ADL (Autoregressive Distributed Lag) models combine lags of GDP Growth Rates as well as lags of the chosen ADL predictor. A maximum of 4 lags of the GDP Growth Rate, and 4 lags of the ADL predictor can be included in the model.
* The combined ADL model considers all the ADL predictors as well as the GDP Growth Rate. A maximum of 2 lags of each variable can be used in the model. 
* Both models select the optimal combination of lags/variables using the Akaike Information Criterion (AIC). Whichever combination has the lowest AIC is chosen as the optimal model. 

&nbsp;

### **Aggregate Models**

* The aggregate model takes the results of 7 models: the revised AR model, the 5 individual ADL models, and the combined ADL model. Using the Granger-Ramanathan test, weights are then evaluated for each of these models, before arriving at a final model that is deemed to be most optimal. The result of this model is what you see for the GDP Growth forecasts. 
* To determine a "poor outlook", the algorithm for the aggregate model flags any indicator that shows at least one negative growth rate for the selected forecast horizon. 
* To determine anomalies, the algorithm highlights 3 different behaviours, leveraging concepts of the Median Average Deviation (MAD) and the median value:
+ When any of the growth rates of an ADL indicator from the past 4 quarters is separated from the median value of the indicator by a value greater than 3 x MAD. This is indicated as a "high deviation". 
+ When 2 of the growth rates of an ADL indicator from the past 4 quarters are separated from the median value of the indicator by a value greater than 2 x MAD. This is indicated as a "medium deviation". 
+ When any of the growth rates of at least 2 ADL indicators from the past 4 quarters are separated from the median value of their individual indicator by a value greater than 2 x MAD. This is indicated as a "medium deviation". 


