
```{r import, warning = FALSE, results= "hide", echo = FALSE}

source("inputs.R")
source("GDP Cleaning.R")
source("AR_Model_Functions.R")
source("ADL Data.R")
source("ADL Functions.R")
source("ADL_Rolling.R")
source("Combined ADL Model Functions.R")
source("DM_test.R")

```


# AR MODELS 

## AR: Basic Model

```{r AR basic}

# basic_AR_input HAS to be a MATRIX. 
# we take in GDPGrowth_ts and convert it to a matrix. 

AR_predict_all(as.matrix(GDPGrowth_ts), example_fhorizon, covid_dummy)

```

## AR: Revised Model

```{r Advanced AR model, warning = FALSE}

advanced_AR_input = adv_ar_input(RGDP_Data, example_startq, example_endq)

advanced_AR_output <- fitAR(advanced_AR_input, example_fhorizon, covid_dummy)

ar2_prediction = advanced_AR_output$pred
ar2_rmsfe = advanced_AR_output$rmsfe

```

## AR: DM Test

```{r AR dm test, warning = FALSE}

pred2 = rolling_window_adv(RGDP_Data, window_start, covid_dummy, real_values, example_startyq, example_endyq)$pred

dm_test_result = dm_test(tail(real_values, window_length), pred1, pred2, window_start, example_endyq)[1]
# Basic vs Advanced values, Plots loss of basic - loss of advanced

p_value = pt(dm_test_result, df = window_length - 1) * 100

dm_test_result
p_value

```



# ADL MODELS 

## ADL: BAA-AAA Spread 

```{r adl model baa-aaa}

ADL_predict_all(GDPGrowth_ts, baa_aaa_ts, example_startq,
                example_endq, example_fhorizon, covid_dummy)

```

## ADL: Treasury Spread 

```{r adl model treasury}

ADL_predict_all(GDPGrowth_ts, tspread_ts, example_startq,
                example_endq, example_fhorizon, covid_dummy)

```

## ADL: Housing Starts

```{r adl model hstarts}

ADL_predict_all(GDPGrowth_ts, hstarts_ts, example_startq,
                example_endq, example_fhorizon, covid_dummy)

```

## ADL: Consumer Sentiment

```{r adl model consent}

ADL_predict_all(GDPGrowth_ts, consent_ts, example_startq,
                example_endq, example_fhorizon, covid_dummy)

```

## ADL: NASDAQ Composite Index 

```{r adl model nasdaq}

ADL_predict_all(GDPGrowth_ts, nasdaq_ts, example_startq,
                example_endq, example_fhorizon, covid_dummy)

```

## ADL: Unemployment Insurance Claims

```{r adl model unemp}

ADL_predict_all(GDPGrowth_ts, unemp_ts, example_startq,
                example_endq, example_fhorizon, covid_dummy)

```


## ADL: Yield Curve 

```{r adl model yield}

ADL_predict_all(GDPGrowth_ts, yield_ts, example_startq,
                example_endq, example_fhorizon, covid_dummy)

```


## ADL: Rolling Window

```{r adl rolling-window, warning = FALSE}

rw_baa = rolling_window_adl(perc_change_df_spliced, baa_aaa_ts, window_start, covid_dummy, real_values, example_startyq, example_endyq)
rw_tsp = rolling_window_adl(perc_change_df_spliced, tspread_ts, window_start, covid_dummy, real_values, example_startyq, example_endyq)
rw_hstarts = rolling_window_adl(perc_change_df_spliced, hstarts_ts, window_start, covid_dummy, real_values, example_startyq, example_endyq)
rw_consent = rolling_window_adl(perc_change_df_spliced, consent_ts, window_start, covid_dummy, real_values, example_startyq, example_endyq)
rw_nasdaq = rolling_window_adl(perc_change_df_spliced, nasdaq_ts, window_start, covid_dummy, real_values, example_startyq, example_endyq)
rw_unemp = rolling_window_adl(perc_change_df_spliced, unemp_ts, window_start, covid_dummy, real_values, example_startyq, example_endyq)
rw_yield = rolling_window_adl(perc_change_df_spliced, yield_ts, window_start, covid_dummy, real_values, example_startyq, example_endyq)

```

```{r adl dm test}

rw_baa$formula
rw_tsp$formula
rw_hstarts$formula
rw_consent$formula
rw_nasdaq$formula
rw_unemp$formula
rw_yield$formula

pred2 = rw_yield$pred

dm_test_result = dm_test(tail(real_values, window_length), pred1, pred2, window_start, example_endyq)[1]
# Basic vs Advanced values, Plots loss of basic - loss of advanced

p_value = pt(dm_test_result, df = window_length - 1) * 100

dm_test_result
p_value

```




# Combined ADL Model

```{r combined adl}

# NEED TO FORM THE COMBINED DATASET FIRST
X_comb_df <- ts.union(baa_aaa_ts, tspread_ts, hstarts_ts, consent_ts, nasdaq_ts) 
# set colnames 
colnames(X_comb_df) <- ADL_variables


ADL_comb_predict_all(GDPGrowth_ts, X_comb_df, ADL_variables, 
                 example_startq, example_endq, example_fhorizon, covid_dummy)

```

## Combined ADL Model: DM Test

```{r combined adl dm test}

rw_comb = rolling_window_comb_adl(perc_change_df_spliced, X_comb_df, window_start, covid_dummy, real_values, example_startyq, example_endyq)
rw_comb$formula

pred2 = rw_comb$pred

dm_test_result = dm_test(tail(real_values, window_length), pred1, pred2, window_start, example_endyq)[1]
# Basic vs Advanced values, Plots loss of basic - loss of advanced

p_value = pt(dm_test_result, df = window_length - 1) * 100

dm_test_result
p_value

```


# Aggregate Model 

```{r aggregate test}

aggregate_output(GDPGrowth_ts, ADL_variables, example_startq, 
                 example_endq, example_fhorizon, covid_dummy)

```
