
```{r import, warning = FALSE, results= "hide", echo = FALSE}

source("inputs.R")
#source("GDP Cleaning.R")
source("GDP Cleaning Functions.R")
source("AR_Model_Functions.R")
#source("ADL Data.R")
source("ADL Data Functions.R")
source("ADL Functions.R")
source("ADL_Rolling.R")
source("DM_test.R")
source("Combined ADL Functions.R")
source("Aggregate Functions.R")

library(tidyverse)
library(ggplot2)
library(zoo)
library(dplyr)
library(shinyWidgets)
library(shinythemes)
library(readxl)
library(xts)
library(AICcmodavg)
library(fresh)
library(RColorBrewer)
library(dynlm)
library(markdown)
library(DT)
library(lsei)
library(sandwich)


RGDP_Data <- read_excel("../Data/RGDP Data.xlsx")

check <- basic_cleaning(RGDP_Data)$check
perc_change_df <- basic_cleaning(RGDP_Data)$perc_change_df
covid = c("2020 Q2", "2020 Q3")
covid_start = as.yearqtr(covid[1])
covid_end = as.yearqtr(covid[2])

ADL_variables <- c("baa_aaa_ts", "tspread_ts", "hstarts_ts", "consent_ts", 
                   "nasdaq_ts")


# defining ADL predictors

baa_aaa <- read_excel("../Data/FRED BAA-AAA Data.xls", 
                      col_names = c("Date", "Spread")) %>% 
  mutate(Date = as.yearqtr(Date), 
         Spread = as.numeric(Spread))

baa_aaa <- ADL_splice(baa_aaa, example_startyq, example_endyq)

tspread <- read_excel("../Data/FRED Treasury Spread.xls", col_names = c("Date", "Spread")) %>% 
  mutate(Date = as.yearqtr(Date), 
         Spread = as.numeric(Spread))

tspread <- ADL_splice(tspread, example_startyq, example_endyq)

hstarts <- read_excel("../Data/FRED Hstarts.xls", col_names = c("Date", "Spread")) %>% 
  mutate(Date = as.yearqtr(Date), 
         Spread = as.numeric(Spread))

hstarts <- ADL_splice(hstarts, example_startyq, example_endyq)

consent <- read_excel("../Data/FRED Consumer Sentiment.xls", col_names = c("Date", "Spread")) %>% 
  mutate(Date = as.yearqtr(Date), 
         Spread = as.numeric(Spread))

consent <- ADL_splice(consent, example_startyq, example_endyq)

nasdaq <- read_excel("../Data/NASDAQCOM.xls", col_names = c("Date", "Spread")) %>% 
  mutate(Date = as.yearqtr(Date), 
         Spread = as.numeric(Spread))

nasdaq <- ADL_splice(nasdaq, example_startyq, example_endyq)

GDP_prep <- GDP_prep(RGDP_Data, example_startq, example_endq)
GDPGrowth_ts <- GDP_prep$GDPGrowth_ts
all_GDP_data <- GDP_prep$all_GDP_data
spliced_GDP <- GDP_prep$spliced_GDP
sliced_perc_change <- GDP_prep$sliced_perc_change
perc_change_df <- basic_cleaning(RGDP_Data)$perc_change_df

covid_dummy = rep(0, (example_endyq - example_startyq) * 4 + 1)
        
# Dummy if timeframe ends on 2020 Q2, start of covid
if (example_startyq <= covid_start & example_endyq == covid_start){
  index = (covid_start - example_startyq) * 4 + 1
  covid_dummy[index] = -1
}

# Dummy if timeframe includes all of covid
if (example_startyq <= covid_start & example_endyq >= covid_end){
  index = (covid_start - example_startyq) * 4 + 1
  covid_dummy[index] = -1
  covid_dummy[index + 1] = 1
}


covid_dummy_ts <- ts(covid_dummy,
                     start = c(start_y, start_q), 
                     end = c(end_y, end_q), 
                     frequency = 4)

baa_aaa_ts <- ts(baa_aaa$Spread, 
                 start = c(start_y, start_q), 
                 end = c(end_y, end_q), 
                 frequency = 4)

tspread_ts <- ts(tspread$Spread, 
                 start = c(start_y, start_q), 
                 end = c(end_y, end_q), 
                 frequency = 4)

hstarts_ts <- ts(hstarts$Spread, 
                      start = c(start_y, start_q), 
                      end = c(end_y, end_q), 
                      frequency = 4)

consent_ts <- ts(consent$Spread, 
                 start = c(start_y, start_q), 
                 end = c(end_y, end_q), 
                 frequency = 4)

nasdaq_ts <- ts(nasdaq$Spread, 
                 start = c(start_y, start_q), 
                 end = c(end_y, end_q), 
                 frequency = 4)
```

# AR MODELS 

## AR: Basic Model

```{r AR basic}

# basic_AR_input HAS to be a MATRIX. 
# we take in GDPGrowth_ts and convert it to a matrix. 

basic_AR_output <- AR_predict_all(as.matrix(GDPGrowth_ts), example_fhorizon, covid_dummy)

```

## AR: Revised Model

```{r Advanced AR model, warning = FALSE}

perc_change_df <- basic_cleaning(RGDP_Data)$perc_change_df

advanced_AR_input = adv_ar_input(RGDP_Data, perc_change_df, example_startq, example_endq)
revised_AR_output <- AR_predict_all(advanced_AR_input, example_fhorizon, covid_dummy)

```

## AR: DM Test

```{r AR dm test, warning = FALSE}

start_rownum = which(grepl(example_startyq, check$Time))
end_rownum = which(grepl(example_endyq, check$Time))

row_start_slice = (example_startyq - as.yearqtr("1947 Q2"))*4 + 1
row_last_slice = nrow(check) - (as.yearqtr("2023 Q4") - example_endyq)*4

real_values = as.matrix(check[row_start_slice:row_last_slice, ncol(check)])
perc_change_df_spliced = perc_change_df[start_rownum:end_rownum,]

pred1 = rolling_window(perc_change_df_spliced, window_start, covid_dummy, real_values, example_startyq, example_endyq)$pred

pred2 = rolling_window_adv(RGDP_Data, perc_change_df, window_start, covid_dummy, real_values, example_startyq, example_endyq)$pred

dm_test_result = dm_test(tail(real_values, window_length), pred1, pred2, window_start, example_endyq)[1]
# Basic vs Advanced values, Plots loss of basic - loss of advanced

p_value = pt(dm_test_result, df = window_length - 1) * 100

dm_test_result
p_value

```



# ADL MODELS 

## ADL: BAA-AAA Spread 

```{r adl model baa-aaa}

test <- ADL_predict_all(GDPGrowth_ts, baa_aaa_ts, example_startq,
                example_endq, 4, covid_dummy)
test$predictions
test$rmsfe

```

## ADL: Treasury Spread 

```{r adl model treasury}

test2 <- ADL_predict_all(GDPGrowth_ts, tspread_ts, example_startq,
                example_endq, 4, covid_dummy)

test2$predictions
test2$rmsfe

```

## ADL: Housing Starts

```{r adl model hstarts}

test3 <- ADL_predict_all(GDPGrowth_ts, hstarts_ts, example_startq,
                example_endq, 4, covid_dummy)

test3$predictions
test3$rmsfe

```

## ADL: Consumer Sentiment

```{r adl model consent}

ADL_predict_all(GDPGrowth_ts, consent_ts, example_startq,
                example_endq, example_fhorizon, covid_dummy)

```

## ADL: NASDAQ Composite Index 

```{r adl model nasdaq}

ADL_predict_all(GDPGrowth_ts, nasdaq_ts, example_startq,
                example_endq, 1, covid_dummy)

```


## ADL: Rolling Window

```{r adl rolling-window, warning = FALSE}

rw_baa = rolling_window_adl(perc_change_df_spliced, baa_aaa_ts, window_start, covid_dummy, real_values, example_startyq, example_endyq)
rw_tsp = rolling_window_adl(perc_change_df_spliced, tspread_ts, window_start, covid_dummy, real_values, example_startyq, example_endyq)
rw_hstarts = rolling_window_adl(perc_change_df_spliced, hstarts_ts, window_start, covid_dummy, real_values, example_startyq, example_endyq)
rw_consent = rolling_window_adl(perc_change_df_spliced, consent_ts, window_start, covid_dummy, real_values, example_startyq, example_endyq)
rw_nasdaq = rolling_window_adl(perc_change_df_spliced, nasdaq_ts, window_start, covid_dummy, real_values, example_startyq, example_endyq)

```

```{r adl dm test}

rw_options = list(rw_baa, rw_tsp, rw_hstarts, rw_consent, rw_nasdaq)
dm_results = rep(0, length(rw_options))
p_value_results = rep(0, length(rw_options))

for (i in 1:length(rw_options)){
  current = rw_options[[i]]
  print(paste("Formula is", as.character(current$formula)))
  
  pred2 = current$pred
  
  dm_test_result = dm_test(tail(real_values, window_length), 
                           pred1, pred2, window_start, example_endyq)[1]
  
  p_value = pt(dm_test_result, df = window_length - 1) * 100
  
  dm_results[i] = dm_test_result
  p_value_results[i] = p_value
}

dm_results
p_value_results

```




# Combined ADL Model

```{r combined adl}

X_comb_df <- ts.union(baa_aaa_ts, tspread_ts, hstarts_ts, consent_ts, nasdaq_ts) 
# set colnames 
colnames(X_comb_df) <- ADL_variables

ADL_comb_predict_all(GDPGrowth_ts, X_comb_df, ADL_variables, 
                 example_startq, example_endq, 1, covid_dummy)

```

## Combined ADL Model: DM Test

```{r combined adl dm test}

rw_comb = rolling_window_comb_adl(perc_change_df_spliced, X_comb_df, window_start, covid_dummy, real_values, example_startyq, example_endyq)
rw_comb$formula

pred2 = rw_comb$pred

dm_test_result = dm_test(tail(real_values, window_length), pred1, pred2, window_start, example_endyq)[1]
# Basic vs Advanced values, Plots loss of basic - loss of advanced

p_value = pt(dm_test_result, df = window_length - 1) * 100

dm_test_result
p_value

```


# Aggregate Model 

```{r aggregate test}

# perc_change_df_spliced
start_rownum = which(grepl(example_startyq, check$Time))
end_rownum = which(grepl(example_endyq, check$Time))

row_start_slice = (example_startyq - as.yearqtr("1947 Q2"))*4 + 1
row_last_slice = nrow(check) - (as.yearqtr("2023 Q4") - example_endyq)*4

real_values = as.matrix(check[row_start_slice:row_last_slice, ncol(check)])
perc_change_df_spliced = perc_change_df[start_rownum:end_rownum,]
        

# X_comb_df 
X_comb_df <- ts.union(baa_aaa_ts, tspread_ts, hstarts_ts, consent_ts, nasdaq_ts) 
# set colnames 
colnames(X_comb_df) <- ADL_variables


aggregate_output(GDPGrowth_ts, X_comb_df, RGDP_Data, 
                 perc_change_df, perc_change_df_spliced, real_values,
                 ADL_variables, example_startq, example_endq, example_fhorizon, covid_dummy,
                 baa_aaa_ts, tspread_ts, hstarts_ts, consent_ts, nasdaq_ts)


```
